In [1]:
# to set up AWS CLI
#https://www.youtube.com/c/Try2Catch/playlists

In [4]:
#!/usr/bin/python

# Copyright 2017-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0

# Import modules
from   loremipsum import get_sentences
import boto3
import names
import random
import string
import signal
import math
import time
import sys

# Global variables
dynamodb_table  = "lambdaTrigger"
provisioned_wcu = 1

# Initiate DynamoDB client
client = boto3.client('dynamodb')

# Signal handler, Ctrl+c to quit
def signal_handler(signal, frame):
    print ("\n")
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)

# Actions
insert_to_ddb   = True;
print_to_screen = True;

# Start the loop to generate simulated tweets
while(True) :
    # Generate fake tweet
    connection    = names.get_first_name()
    password   = str(random.randint(pow(10,16),pow(10,17)-1))
#     created_at = time.strftime("%a %b %d %H:%M:%S +0000 %Y", time.gmtime())
#     language   = random.choice(['de', 'en', 'es', 'fr', 'id', 'nl', 'pt', 'sk'])
#     text       = str(get_sentences(1)[0])

    # Store tweet in DynamoDB
    if insert_to_ddb == True :
        res = client.put_item(
          TableName=dynamodb_table,
            Item={
              'connection'   : { 'S' : connection    },
              'password'  : { 'N' : password   }
#               'created_at': { 'S' : created_at },
#               'language'  : { 'S' : language   },
#               'text'      : { 'S' : text       }
              })

    # Print output to screen
    if print_to_screen == True :
        print ("insert_to_ddb: %s" % insert_to_ddb)
        print ("connection      : %s" % connection)
        print ("password     : %d" % int(password))
#         print "created_at   : %s" % created_at
#         print "language     : %s" % language
#         print "text         : %s" % (text[:77] + '...' if len(text) > 80 else text)
        print ("\n===========================================")

    # Loop control
    time.sleep(1.0/provisioned_wcu)

insert_to_ddb: True
connection      : Joyce
password     : 51029089978243193

===========================================
insert_to_ddb: True
connection      : Dana
password     : 43003897449027135

===========================================
insert_to_ddb: True
connection      : Richard
password     : 66205509239444927

===========================================
insert_to_ddb: True
connection      : Crystal
password     : 69404580088033279

===========================================
insert_to_ddb: True
connection      : Donald
password     : 97952694103900894

===========================================
insert_to_ddb: True
connection      : Michael
password     : 98760225357975413

===========================================
insert_to_ddb: True
connection      : Anthony
password     : 87023581358743355

===========================================
insert_to_ddb: True
connection      : Lawrence
password     : 87431818095461865

===========================================
insert_to_ddb: True
connection      : Edward
password     : 45092171948532230

===========================================
insert_to_ddb: True
connection      : Raymond
password     : 80998529007726989

===========================================
insert_to_ddb: True
connection      : Viola
password     : 50915007126358079

===========================================
insert_to_ddb: True
connection      : Iola
password     : 76938879450763767

===========================================
insert_to_ddb: True
connection      : Mario
password     : 86413829774284690

===========================================
insert_to_ddb: True
connection      : Gerald
password     : 92275534831226521

===========================================
insert_to_ddb: True
connection      : Beatrice
password     : 67550462311483775

===========================================
insert_to_ddb: True
connection      : Joanie
password     : 86832460384342370

===========================================
insert_to_ddb: True
connection      : Ashley
password     : 93526807567740360

===========================================
insert_to_ddb: True
connection      : Andre
password     : 39027493712404281

===========================================
insert_to_ddb: True
connection      : Janet
password     : 73790402234077556

===========================================
insert_to_ddb: True
connection      : Michael
password     : 50214961041586332

===========================================
insert_to_ddb: True
connection      : Caroline
password     : 13635905772984985

===========================================
insert_to_ddb: True
connection      : Linda
password     : 14625102869898920

===========================================
insert_to_ddb: True
connection      : Darin
password     : 47441254120560893

===========================================
insert_to_ddb: True
connection      : Melissa
password     : 37676462252153677

===========================================
insert_to_ddb: True
connection      : Sandra
password     : 60714322763126622

===========================================
insert_to_ddb: True
connection      : Bryan
password     : 11956748152090701

===========================================
insert_to_ddb: True
connection      : Bonnie
password     : 17335439576973238

===========================================
insert_to_ddb: True
connection      : Cheri
password     : 19230490336799294

===========================================
insert_to_ddb: True
connection      : Angela
password     : 37789003171629462

===========================================
insert_to_ddb: True
connection      : Winifred
password     : 83759279142555719

===========================================
insert_to_ddb: True
connection      : Elizabeth
password     : 15382754476861676

===========================================
insert_to_ddb: True
connection      : Nancy
password     : 59514464638927297

===========================================
insert_to_ddb: True
connection      : Shannon
password     : 83410129225358136

===========================================
insert_to_ddb: True
connection      : Irving
password     : 32307975337703791

===========================================
insert_to_ddb: True
connection      : Michael
password     : 70931745649218176

===========================================
insert_to_ddb: True
connection      : Elaine
password     : 56066700473269295

===========================================
insert_to_ddb: True
connection      : Marita
password     : 47614155556541597

===========================================
insert_to_ddb: True
connection      : Mable
password     : 89498997310494906

===========================================
insert_to_ddb: True
connection      : Sharon
password     : 19881040389989916

===========================================
insert_to_ddb: True
connection      : Judy
password     : 78895436139506107

===========================================
insert_to_ddb: True
connection      : Jack
password     : 15973303544718700

===========================================
insert_to_ddb: True
connection      : Linda
password     : 81653531788951405

===========================================
insert_to_ddb: True
connection      : Edith
password     : 57078870947941120

===========================================
insert_to_ddb: True
connection      : Jeannette
password     : 90688512744159000

===========================================
insert_to_ddb: True
connection      : Kevin
password     : 34518696946995999

===========================================
insert_to_ddb: True
connection      : Zachary
password     : 32938695567808893

===========================================
insert_to_ddb: True
connection      : Margie
password     : 56603169498980035

===========================================
insert_to_ddb: True
connection      : Gregory
password     : 17955488325911326

===========================================
insert_to_ddb: True
connection      : Susan
password     : 38608753207260700

===========================================
insert_to_ddb: True
connection      : Chad
password     : 56950236321397450

===========================================
insert_to_ddb: True
connection      : Misty
password     : 63851533599465144

===========================================
insert_to_ddb: True
connection      : Melinda
password     : 17319877712940085

===========================================
insert_to_ddb: True
connection      : Glenn
password     : 84374779457006971

===========================================
insert_to_ddb: True
connection      : Velma
password     : 17999547867621728

===========================================
insert_to_ddb: True
connection      : Reginald
password     : 14208295597804938

===========================================
insert_to_ddb: True
connection      : Rhonda
password     : 63714481741571573

===========================================
insert_to_ddb: True
connection      : Carole
password     : 14735706931839580

===========================================
insert_to_ddb: True
connection      : Kelly
password     : 94606850932222308

===========================================
insert_to_ddb: True
connection      : Michael
password     : 18014876772741873

===========================================
insert_to_ddb: True
connection      : Ronald
password     : 53971448974497423

===========================================
insert_to_ddb: True
connection      : Stephen
password     : 19244060864439744

===========================================
insert_to_ddb: True
connection      : Bryan
password     : 24943491331754659

===========================================
insert_to_ddb: True
connection      : Charles
password     : 46168853414359942

===========================================
insert_to_ddb: True
connection      : Jennifer
password     : 65647845282011669

===========================================
insert_to_ddb: True
connection      : David
password     : 62271315765375120

===========================================
insert_to_ddb: True
connection      : Christine
password     : 11684657640296000

===========================================
insert_to_ddb: True
connection      : Bernard
password     : 50243022463913629

===========================================

insert_to_ddb: True
connection      : Martha
password     : 70155693020082241

===========================================
insert_to_ddb: True
connection      : Jeanette
password     : 25210477560210946

===========================================
insert_to_ddb: True
connection      : Anthony
password     : 50964892814526062

===========================================
insert_to_ddb: True
connection      : Patrick
password     : 56747846469557117

===========================================
insert_to_ddb: True
connection      : Katelyn
password     : 92829787363723702

===========================================
insert_to_ddb: True
connection      : Stephen
password     : 17721560034120742

===========================================
insert_to_ddb: True
connection      : William
password     : 71901281781061238

===========================================
insert_to_ddb: True
connection      : Rosalie
password     : 91209304525649088

===========================================
insert_to_ddb: True
connection      : April
password     : 12289359587089989

===========================================
insert_to_ddb: True
connection      : Albert
password     : 29931080492395359

===========================================
insert_to_ddb: True
connection      : Shelly
password     : 96047066618717951

===========================================
insert_to_ddb: True
connection      : Thelma
password     : 28686382189195309

===========================================
insert_to_ddb: True
connection      : Essie
password     : 29280635158210365

===========================================
insert_to_ddb: True
connection      : Krista
password     : 29392825890239482

===========================================
insert_to_ddb: True
connection      : Esther
password     : 69994866115962362

===========================================
insert_to_ddb: True
connection      : Daniel
password     : 11498838436269030

===========================================
insert_to_ddb: True
connection      : Jennifer
password     : 12741461845460672

===========================================
insert_to_ddb: True
connection      : Linda
password     : 77998492855937348

===========================================
insert_to_ddb: True
connection      : John
password     : 97394017562351137

===========================================
insert_to_ddb: True
connection      : Marc
password     : 33234889526232148

===========================================
insert_to_ddb: True
connection      : John
password     : 94442168506954122

===========================================
insert_to_ddb: True
connection      : Brian
password     : 25961899619925978

===========================================
insert_to_ddb: True
connection      : Jack
password     : 45024131524360982

===========================================
insert_to_ddb: True
connection      : Phillip
password     : 33720278609756966

===========================================
insert_to_ddb: True
connection      : Lisa
password     : 63712650174860873

===========================================
insert_to_ddb: True
connection      : Byron
password     : 98534688277432298

===========================================
insert_to_ddb: True
connection      : Don
password     : 38440485611198606

===========================================
insert_to_ddb: True
connection      : James
password     : 97712774580264500

===========================================
insert_to_ddb: True
connection      : Janice
password     : 93527374033096746

===========================================
insert_to_ddb: True
connection      : Rachael
password     : 56544890719134164

===========================================
insert_to_ddb: True
connection      : Leslie
password     : 17293503676011034

===========================================
insert_to_ddb: True
connection      : Anthony
password     : 24806778201802703

===========================================
insert_to_ddb: True
connection      : Mark
password     : 50497179828368489

===========================================
insert_to_ddb: True
connection      : Eula
password     : 90653390310782657

===========================================
insert_to_ddb: True
connection      : George
password     : 30233847649663407

===========================================
insert_to_ddb: True
connection      : Tandra
password     : 83631497402807519

===========================================
insert_to_ddb: True
connection      : Cathy
password     : 69643926119072499

===========================================
insert_to_ddb: True
connection      : Shelia
password     : 73228775710762189

===========================================
insert_to_ddb: True
connection      : Kelly
password     : 22838661496860482

===========================================
insert_to_ddb: True
connection      : Michelle
password     : 77586668915432938

===========================================
insert_to_ddb: True
connection      : Martha
password     : 91852250240510364

===========================================
insert_to_ddb: True
connection      : Rosemary
password     : 46228340298728701

===========================================
insert_to_ddb: True
connection      : Harold
password     : 54559601448151654

===========================================
insert_to_ddb: True
connection      : David
password     : 13759848403655564

===========================================
insert_to_ddb: True
connection      : Betty
password     : 39961299050235463

===========================================
insert_to_ddb: True
connection      : Denny
password     : 32176574898671869

===========================================
insert_to_ddb: True
connection      : Ruby
password     : 86345611084851862

===========================================
insert_to_ddb: True
connection      : George
password     : 51823012880224568

===========================================
insert_to_ddb: True
connection      : Katie
password     : 29640433370529105

===========================================
insert_to_ddb: True
connection      : Adam
password     : 57160966668659386

===========================================
insert_to_ddb: True
connection      : Genoveva
password     : 61178603191150275

===========================================
insert_to_ddb: True
connection      : Alicia
password     : 96454700080887587

===========================================
insert_to_ddb: True
connection      : Donald
password     : 93029238655185096

===========================================
insert_to_ddb: True
connection      : Alfred
password     : 89076752008614627

===========================================
insert_to_ddb: True
connection      : Anthony
password     : 44984243790901218

===========================================
insert_to_ddb: True
connection      : Evan
password     : 82843637528796175

===========================================
insert_to_ddb: True
connection      : Robert
password     : 87390094146222583

===========================================
insert_to_ddb: True
connection      : Barbara
password     : 63677297965865173

===========================================
insert_to_ddb: True
connection      : Maria
password     : 69127417121324379

===========================================
insert_to_ddb: True
connection      : Ellie
password     : 36934084582890324

===========================================
insert_to_ddb: True
connection      : Joshua
password     : 27904609033790261

===========================================
insert_to_ddb: True
connection      : Maria
password     : 79872989764655553

===========================================
insert_to_ddb: True
connection      : Sarah
password     : 89258516038646840

===========================================
insert_to_ddb: True
connection      : John
password     : 73430043306174272

===========================================
insert_to_ddb: True
connection      : Terri
password     : 36474244818124902

===========================================
insert_to_ddb: True
connection      : Karin
password     : 41938536151482316

===========================================
insert_to_ddb: True
connection      : Darin
password     : 49341530192398252

===========================================

insert_to_ddb: True
connection      : Lorraine
password     : 39803404578712830

===========================================
insert_to_ddb: True
connection      : Melanie
password     : 49230899225447864

===========================================
insert_to_ddb: True
connection      : Majorie
password     : 30343959192680915

===========================================
insert_to_ddb: True
connection      : Michael
password     : 99256832601493696

===========================================
insert_to_ddb: True
connection      : Christine
password     : 53168914177097081

===========================================
insert_to_ddb: True
connection      : Wanda
password     : 55396856901378203

===========================================
insert_to_ddb: True
connection      : Carrie
password     : 37449999086388657

===========================================
insert_to_ddb: True
connection      : James
password     : 74250004054003350

===========================================
insert_to_ddb: True
connection      : Dollie
password     : 88105661502238840

===========================================
insert_to_ddb: True
connection      : Gregory
password     : 32035620559713833

===========================================
insert_to_ddb: True
connection      : Brian
password     : 42589069238397929

===========================================
insert_to_ddb: True
connection      : Linda
password     : 69095316062373741

===========================================
insert_to_ddb: True
connection      : Luz
password     : 28176806660498259

===========================================
insert_to_ddb: True
connection      : Juanita
password     : 28475758512785405

===========================================
insert_to_ddb: True
connection      : David
password     : 88913472120412356

===========================================
insert_to_ddb: True
connection      : Margaret
password     : 68030990242842809

===========================================
insert_to_ddb: True
connection      : Marion
password     : 71719915813699172

===========================================
insert_to_ddb: True
connection      : Christopher
password     : 57727447057274363

===========================================
insert_to_ddb: True
connection      : Yvette
password     : 58795522624972604

===========================================
insert_to_ddb: True
connection      : Felicia
password     : 35593238059877503

===========================================
insert_to_ddb: True
connection      : Gladys
password     : 48649094282939852

===========================================
insert_to_ddb: True
connection      : Nicole
password     : 23924437507203900

===========================================
insert_to_ddb: True
connection      : Shirleen
password     : 82167212896120212

===========================================
insert_to_ddb: True
connection      : Lena
password     : 24818227469132303

===========================================
insert_to_ddb: True
connection      : Donald
password     : 67349930937919584

===========================================
insert_to_ddb: True
connection      : Michael
password     : 16506266526895741

===========================================
insert_to_ddb: True
connection      : Arden
password     : 73687801336892751

===========================================
insert_to_ddb: True
connection      : Rosa
password     : 33343687049489460

===========================================
insert_to_ddb: True
connection      : Charlie
password     : 14624265711500309

===========================================
insert_to_ddb: True
connection      : Bella
password     : 19501493546993155

===========================================
insert_to_ddb: True
connection      : Jeffery
password     : 25639712087828099

===========================================
insert_to_ddb: True
connection      : Aurelio
password     : 29725232521255614

===========================================
insert_to_ddb: True
connection      : Johanna
password     : 68681623447671854

===========================================
insert_to_ddb: True
connection      : Eugene
password     : 48301776442623061

===========================================
insert_to_ddb: True
connection      : Jane
password     : 98978067925647913

===========================================
insert_to_ddb: True
connection      : Douglas
password     : 10517587441733563

===========================================
insert_to_ddb: True
connection      : Robin
password     : 20733862978117436

===========================================
insert_to_ddb: True
connection      : Russell
password     : 42612564388175900

===========================================
insert_to_ddb: True
connection      : John
password     : 54849283047006739

===========================================
insert_to_ddb: True
connection      : Bryant
password     : 58609928854167761

===========================================
insert_to_ddb: True
connection      : Sandra
password     : 13370186502722363

===========================================
insert_to_ddb: True
connection      : Vicki
password     : 81752835791242900

===========================================
insert_to_ddb: True
connection      : Clyde
password     : 64077764233735298

===========================================
insert_to_ddb: True
connection      : Sandra
password     : 94191493231259676

===========================================
insert_to_ddb: True
connection      : William
password     : 37858058573751377

===========================================
insert_to_ddb: True
connection      : David
password     : 62699988191082232

===========================================
insert_to_ddb: True
connection      : Billie
password     : 15816157368400520

===========================================
insert_to_ddb: True
connection      : David
password     : 77987943031226050

===========================================
insert_to_ddb: True
connection      : Joseph
password     : 73741355599603021

===========================================
insert_to_ddb: True
connection      : John
password     : 41867884091697354

===========================================
insert_to_ddb: True
connection      : Arturo
password     : 42895935017948377

===========================================
insert_to_ddb: True
connection      : Carmela
password     : 45356419029045527

===========================================
insert_to_ddb: True
connection      : May
password     : 52938443028076216

===========================================
insert_to_ddb: True
connection      : George
password     : 80038271604135644

===========================================
insert_to_ddb: True
connection      : Selena
password     : 83521044192360215

===========================================
insert_to_ddb: True
connection      : Genevieve
password     : 81293076167432725

===========================================
insert_to_ddb: True
connection      : Sarah
password     : 86890543592568615

===========================================
insert_to_ddb: True
connection      : Valerie
password     : 29749243892467563

===========================================
insert_to_ddb: True
connection      : Dorothy
password     : 87678999012509528

===========================================
insert_to_ddb: True
connection      : Audra
password     : 72947204146495974

===========================================
insert_to_ddb: True
connection      : John
password     : 79528156946119511

===========================================
insert_to_ddb: True
connection      : Jessie
password     : 86553021457069771

===========================================
insert_to_ddb: True
connection      : Gary
password     : 95052311340215340

===========================================
insert_to_ddb: True
connection      : Stephen
password     : 95196110955049280

===========================================
insert_to_ddb: True
connection      : Robert
password     : 60759385456501008

===========================================
insert_to_ddb: True
connection      : Karen
password     : 86982511995748247

===========================================
insert_to_ddb: True
connection      : Steven
password     : 44851976993450541

===========================================

insert_to_ddb: True
connection      : Joshua
password     : 24003354106326363

===========================================
insert_to_ddb: True
connection      : Gary
password     : 28618330942496809

===========================================
insert_to_ddb: True
connection      : Jared
password     : 31628540565680542

===========================================
insert_to_ddb: True
connection      : Paul
password     : 17713425665501366

===========================================
insert_to_ddb: True
connection      : Loretta
password     : 21298029391880822

===========================================
insert_to_ddb: True
connection      : Anita
password     : 19437424351476491

===========================================
insert_to_ddb: True
connection      : Lucille
password     : 58007535913425298

===========================================
insert_to_ddb: True
connection      : Emmett
password     : 73515556313308722

===========================================
insert_to_ddb: True
connection      : Dave
password     : 86472224715689400

===========================================
insert_to_ddb: True
connection      : Ruby
password     : 78116307143801269

===========================================
insert_to_ddb: True
connection      : Neva
password     : 66347558280942577

===========================================
insert_to_ddb: True
connection      : Lacie
password     : 72702457342952248

===========================================
insert_to_ddb: True
connection      : Harry
password     : 56570800370934358

===========================================
insert_to_ddb: True
connection      : Arthur
password     : 26180467469768564

===========================================
insert_to_ddb: True
connection      : Rafael
password     : 78282910226845443

===========================================
insert_to_ddb: True
connection      : Francis
password     : 54794742068802347

===========================================
insert_to_ddb: True
connection      : Craig
password     : 66450176055397215

===========================================
insert_to_ddb: True
connection      : Richard
password     : 37751664504966911

===========================================
insert_to_ddb: True
connection      : Hazel
password     : 54836599893254051

===========================================
insert_to_ddb: True
connection      : Garrett
password     : 85744291924174506

===========================================
insert_to_ddb: True
connection      : David
password     : 74749813325510325

===========================================
insert_to_ddb: True
connection      : Deanna
password     : 21812506844161336

===========================================
insert_to_ddb: True
connection      : Norma
password     : 70583650868131618

===========================================
insert_to_ddb: True
connection      : Addie
password     : 55416322650326675

===========================================
insert_to_ddb: True
connection      : Francisco
password     : 88084501957338208

===========================================
insert_to_ddb: True
connection      : William
password     : 76471531953358061

===========================================
insert_to_ddb: True
connection      : Ronald
password     : 91536770683201881

===========================================
insert_to_ddb: True
connection      : Anthony
password     : 55864837558322340

===========================================
insert_to_ddb: True
connection      : Paul
password     : 84845249972547820

===========================================
insert_to_ddb: True
connection      : Lorrie
password     : 26298041452712078

===========================================
insert_to_ddb: True
connection      : Michael
password     : 23486671866639226

===========================================
insert_to_ddb: True
connection      : Susie
password     : 35810330344538877

===========================================
insert_to_ddb: True
connection      : Mark
password     : 18415037525850268

===========================================
insert_to_ddb: True
connection      : Susan
password     : 46471189489945475

===========================================
insert_to_ddb: True
connection      : Collen
password     : 89353779027134990

===========================================
insert_to_ddb: True
connection      : Todd
password     : 32884623913312690

===========================================
insert_to_ddb: True
connection      : Barry
password     : 86543461091031665

===========================================
insert_to_ddb: True
connection      : Angela
password     : 47304181058491199

===========================================
insert_to_ddb: True
connection      : Patricia
password     : 40447414343578519

===========================================
insert_to_ddb: True
connection      : Gene
password     : 74888042529891539

===========================================
insert_to_ddb: True
connection      : Anna
password     : 53747389865107537

===========================================
insert_to_ddb: True
connection      : Lillian
password     : 42008732571588284

===========================================
insert_to_ddb: True
connection      : Dennis
password     : 27306505978632022

===========================================
insert_to_ddb: True
connection      : Daniel
password     : 26219669352900748

===========================================
insert_to_ddb: True
connection      : Justin
password     : 86389426104437981

===========================================
insert_to_ddb: True
connection      : Jeremy
password     : 48405554712714141

===========================================
insert_to_ddb: True
connection      : Fawn
password     : 17347385465669029

===========================================
insert_to_ddb: True
connection      : Christopher
password     : 50444747768866553

===========================================
insert_to_ddb: True
connection      : Brian
password     : 33554834268766726

===========================================
insert_to_ddb: True
connection      : Jessie
password     : 34529429680950028

===========================================
insert_to_ddb: True
connection      : Jimmy
password     : 11562552481320263

===========================================
insert_to_ddb: True
connection      : Cinthia
password     : 59053879092383178

===========================================
insert_to_ddb: True
connection      : Edward
password     : 58729718871477234

===========================================
insert_to_ddb: True
connection      : Mamie
password     : 69257569879997539

===========================================
insert_to_ddb: True
connection      : Anthony
password     : 62154956250707251

===========================================
insert_to_ddb: True
connection      : Stacy
password     : 79122604069973556

===========================================
insert_to_ddb: True
connection      : Susan
password     : 72388964018823198

===========================================
insert_to_ddb: True
connection      : John
password     : 36710039344415602

===========================================
insert_to_ddb: True
connection      : Charles
password     : 33630802166798260

===========================================
insert_to_ddb: True
connection      : Cindy
password     : 87187985694017141

===========================================
insert_to_ddb: True
connection      : Crystal
password     : 47649865449410914

===========================================
insert_to_ddb: True
connection      : Loren
password     : 92739979038815885

===========================================
insert_to_ddb: True
connection      : Lilliam
password     : 17371358000595769

===========================================

SystemExit: 0

C:\Users\DELL\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3445: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)